### ISSUE TITLE
h_t_probable error

### ISSUE THREAD

**Issue by dhjpolymath** [km-git-acc/dbn_upper_bound#20]
There needs to be a correction in the file:

from

    for i, nearby_root in enumerate(first_1000_H0_zero[l:k]):
        Ht_root = fsolve(Ht_real, nearby_root, args=(t,))[0]
        print(t, i, Ht_root)

to

    for i, nearby_root in enumerate(first_1000_H0_zero[l-1:k-1]):
        Ht_root = fsolve(Ht_real, nearby_root, args=(t,))[0]
        print(t, i, Ht_root)

to shift the indices.

**Comment by sujitnair** [comment]
@km-git-acc 

It makes sense to add @dhjpolymath as a contributor. That way they can work on a branch and send a PR. Thoughts?

@dhjpolymath Until that happens, can you send a PR with the change? Happy to merge it after having a look. Thanks!

**Comment by km-git-acc** [comment]
I think I had added @dhjpolymath as a collaborator, but the invite is still pending. https://github.com/km-git-acc/dbn_upper_bound/invitations
Please check.

**Comment by sujitnair** [comment]
@dhjpolymath 

Can you add yourself to the project and send a PR for this?

**Comment by sujitnair** [comment]
👍
