### ISSUE TITLE
Github Storage

### ISSUE THREAD

**Issue by dhjpolymath** [km-git-acc/dbn_upper_bound#32]
The goal of collecting large zeroes of H_t involves large data files. Github has a file upload limit of 100 MB per file with a recommended repository size of 1 GB. It is likely current data files will be greater in size than either of these limits. Another file sharing client might be used to store/access the large data files.

**Comment by sujitnair** [comment]
@dhjpolymath @km-git-acc 

It is not a good idea to store large files on GitHub. In addition to bloating code base unnecessarily, it also bloats the .git meta data folder.

We should be using AWS S3 or dropbox for now.

**Comment by km-git-acc** [comment]
Yeah, I had the same concerns. Google Drive is a decent option as well.

**Comment by sujitnair** [comment]
Also, please store all the metadata in the storage folder. By that, I mean at least the following

1. git log hash of the code which was used to generate the data
2. range of t and number of zeroes being targetted
