### ISSUE TITLE
Delete old files

### ISSUE THREAD

**Issue by sujitnair** [km-git-acc/dbn_upper_bound#33]
@km-git-acc 

Let's make a list of files that need to be deleted here.

**Comment by sujitnair** [comment]
Have a look at

https://github.com/km-git-acc/dbn_upper_bound/pull/34

@km-git-acc

**Comment by km-git-acc** [comment]
I think this has already been done right? The python folder looks much cleaner.

**Comment by sujitnair** [comment]
Closing this!
