### ISSUE TITLE
Why is H.real being returned

### ISSUE THREAD

**Issue by sujitnair** [km-git-acc/dbn_upper_bound#38]
@km-git-acc 

Why is this in place?
    H = A+B+C
    if z.imag==0: return H.real
    else: return H

Why not just return H?

**Comment by km-git-acc** [comment]
There can always be rounding errors. But we know from theory that H is real when y=0.
For eg. http://michaelnielsen.org/polymath1/index.php?title=De_Bruijn-Newman_constant
(..Ht is even, real on the real axis..)
