### ISSUE TITLE
Experiments with new python files 13 February 2018

### ISSUE THREAD

**Issue by dhjpolymath** [km-git-acc/dbn_upper_bound#43]
Here is the recent output of a run of sample afe_abc_calc with input parameters z=515900 and t=.50

515900.116355...
515901.234721...
515902.382829...
515903.523178...

Compare this with the closest outputs of fast_zero_calc for t=.50 known_root=515857.5795

515900.0916
515901.2057
515902.3756
515903.499

The relative error is about 1e-7 to 1e-8.

**Comment by km-git-acc** [comment]
@dhjpolymath 
Yeah, fast zero calc uses the ridder solver in mpmath to locate roots which is based on Brent's method (a combination of bisection, secant and inverse quadratic interpolation)
https://en.wikipedia.org/wiki/Brent%27s_method 

It is slightly less accurate than the slow but reliable bisection method, but for root finding purposes at large heights in intervals where we have already detected a sign change, it is good enough. Moreover, the relative error between this and bisection decreases as T increases.

Also, I have already found roots between T = 500k and 600k for t=0.5 and 0.4. I can share those files with you. It would be better to run fast calc at either larger heights or for other t. Also, I would recommend not using this for low t such as 0.05 or 0.1. 

A table I had posted at Terry's blog can be used to determine whats the right domain for fast calc (where the normalized stdev of zero gaps is less than 10% (lower the better)).

————-t
T height—-0.50—-0.45—-0.40—-0.35—-0.30—-0.25—-0.20—-0.15—-0.10—-0.05—-0.00
———————————————————————————————-
near 10^3—21.0%—22.2%—23.4%—24.8%—26.3%—27.9%—29.7%—31.7%—33.9%—36.2%—39.2%
near 10^4—13.7%—14.9%—16.7%—18.5%—19.8%—22.0%—24.4%—27.2%—30.6%—34.5%—39.9%
near 10^5—-7.3%—-8.4%—-9.7%—11.2%—13.2%—15.5%—18.3%—21.8%—26.2%—32.0%—40.3%
near 10^6—-4.0%—-4.7%—-5.6%—-6.9%—-8.2%—10.2%—12.9%—16.3%—21.2%—28.1%—40.7%
near 10^7—-2.4%—-2.8%—-3.4%—-4.2%—-5.2%—-6.8%—-8.9%—12.1%—16.3%—23.8%—41.0%

When we want to run it for other ranges of t, T, it's better to use the slower file sample_afe...

**Comment by km-git-acc** [comment]
@djhpolymath
Also, just as a precaution, please use the latest files in the repo (i think the fix of t>0 was applied around a week back so anything after that should be good).

**Comment by km-git-acc** [comment]
Also, once the zeroes are found in a certain range, its a good idea to manually compare the number of zeroes against N_t(T_max)-N_t(T_min). The difference so far has come out to be always less than 1 when the expected number of zeroes were found.
