### ISSUE TITLE
Question regarding Julia scripts

### ISSUE THREAD

**Issue by WilCrofter** [km-git-acc/dbn_upper_bound#6]
@km-git-acc, kind thanks for including [Julia](https://julialang.org/). Somewhat awkwardly for present purposes (centralized code) Julia code is typically packaged in standalone git repositories. Git, in fact, is Julia's package manager. In any case [my (already lagging) Julia port](https://github.com/WilCrofter/DBNUpperBound.jl) of this repository's Python code is packaged in this way.

So, I wonder if I might include just [Jupyter](http://jupyter.org/) notebooks and/or scripts illustrating package installation and use in this folder, keeping the package itself in its own repo. Jupyter notebooks render nicely at Github and, like scripts, can be executed locally. Installation of the package and its dependencies is easy enough, e.g.,
```
julia> Pkg.clone("https://github.com/WilCrofter/DBNUpperBound.jl.git")
```
Once a package is installed, all its source code and documentation is available locally.

**Comment by km-git-acc** [comment]
Yeah no issues. That works.

**Comment by WilCrofter** [comment]
Thanks, @km-git-acc. Afterthought: if in addition to the above you fork my repo and make me a collaborator on the fork I'll keep it current for you. It would be easy enough and would colocate all the source code.

**Comment by km-git-acc** [comment]
Ok. Typing from my phone right now :) but will do that tomorrow.

**Comment by WilCrofter** [comment]
Thank you. Closing the issue.

**Comment by km-git-acc** [comment]
I forked your repo and made you a collaborator on the forked one. Please check on your side.

**Comment by WilCrofter** [comment]
Thank you. Accepted invite. We're all set.
