### ISSUE TITLE
Typo in definition of γ?

### ISSUE THREAD

**Issue by WilCrofter** [km-git-acc/dbn_upper_bound#75]
There may be sign error in your (excellent) paper's definition of γ.  Currently definition (16) reads
```
(16) γ(x+iy) := Mₜ(t,(1-y+i*x)/2)/Mₜ(t,(1+y-i*x)/2)
```
It should, perhaps, read
```
(16) γ(x+iy) := Mₜ(t,(1-y+i*x)/2)/Mₜ(t,(1+y+i*x)/2)
```
IOW, that  `ix/2` should have the same sign in numerator and denominator. The mean value theorem as used in first line of the proof of Proposition 6.6 (estimates) implies, as far as can tell that `log|Mₜ(t,(σ+i*x)/2)|` should be a function of `σ` only which it would not be if the signs of `ix` were different in numerator and denominator.

Apologies if I'm missing something obvious. As far as I've checked computationally, the inequality seems to be true in either case.

**Comment by km-git-acc** [comment]
@WilCrofter 
Is the question addressed to Prof. Tao. It's not clear if Github sends the comment to the mail unless participants are actually marked. You could try doing that or asking on the blog.

**Comment by WilCrofter** [comment]
@km-git-acc thanks for clarifying. I'll close the issue and repost to the blog. It's a trivial matter, but it does look like a sign error.
