### ISSUE TITLE
Issues caused by frequent committing to master

### ISSUE THREAD

**Issue by km-git-acc** [km-git-acc/dbn_upper_bound#9]
@sujitnair - I think I have zeroed down on why the H0 real compute isn't working. The utility file that's imported sent through some change so that complex calculations could be handled. It now imports cmath instead of math. And the exp,pow functions return complex values.

Firstly, as you suggested a proper process to commit to master will have to be established. Reviews by multiple collaborators should weed most problems out.

Secondly, the current utility file now has most of the functions needed for medium z calculations at least. Ht_real is present which subsumes H0_real. Ht_complex is also present, plus some root finding functions.

To compute H0_real values, something like this should work

from utility import *

z=28.26 #or as part of some loop
Ht_real(z,0)

**Comment by sujitnair** [comment]
@km-git-acc 

I started a new branch 
https://github.com/km-git-acc/dbn_upper_bound/tree/refactoring

Have a look at it and let me know if something isn't clear. I added your feedback to H0_real_compute.py

A lot of code should now work in a Python 3.6 virtual environment. Let's work on this and hold off any merges until this branch is taken care of.

Regards,
Sujit

**Comment by sujitnair** [comment]
@km-git-acc I am fine marking this resolved!

**Comment by km-git-acc** [comment]
Have added two new pull requests to remove any dependencies on ht_real_compute.py. Please review and merge.

**Comment by sujitnair** [comment]
@km-git-acc 

I left a comment on the first one. That branch needs a minor change.

**Comment by sujitnair** [comment]
@km-git-acc 

Going back to Terry's comment "how large T needs to be compared with t for these asymptotics to become visible.", what is the numerical strategy?

**Comment by sujitnair** [comment]
@km-git-acc Oops sorry. This issue is probably not the right thread to discuss this.

**Comment by km-git-acc** [comment]
Ok. But one pointer which can help is Gourdon's numerical work for the first 10^13 zeroes. Beyond what T height did the N0(T) symptotics become accurate enough in that exercise? We could be looking at a similar T value atleast for small positive t. And for t near 0.5, the needed T height could be much smaller.
